#+TITLE: README
#+AUTHOR: Lou Jackson
#+DESCRIPTION: README file for git_sync.sh

* TABLE OF CONTENTS :toc:
- [[#about][ABOUT]]
- [[#dependencies][DEPENDENCIES]]
- [[#how-to-use][HOW TO USE]]

* ABOUT
This is a set of scripts that I have been working on for a while to automate syncronizing my personal
git repos, and teach myself how to write conditionals, loops, and functions in Bash.
As I advance in proficiency with Bash, I would like to rework the contents of the script and
make it more portable. I still have alot to learn, so what is here may not be the most efficient
way to go about things.
As it stands at the moment, this script only accounts for the directory structure on my personal systems.
Of course you may feel free to edit any of the variables and create your own as necessary
Later on in development the script will be rewritten so that it may "install" itself.
Creating the appropriate files and directories if they are not found on the system.
Maybe you will find it useful too!

* DEPENDENCIES
GNU Core Utils, Bash, Open-SSH, and Git. That's it!

* HOW TO USE

Begin by cloning the repo into your home directory, then add it to "$PATH".

#+begin_src bash
git clone https://github.com/loujackson902/git_sync.git $HOME
#+end_src

Either source .profile, or restart your terminal.

#+begin_src bash
source $HOME/.profile

## Or use the shorthand
. $HOME/.profile

#+end_src

Make sure to generate some ssh keys to use with Git if you haven't already, then add the path to those keys to your .ssh/config file.
Don't forget to add them to Github/Gitlab.

#+begin_src bash
ssh-keygen -f $HOME/.ssh/NAME_OF_KEY

echo "IdentityFile $HOME/.ssh/NAME_OF_KEY" >> $HOME/.ssh/config
#+end_src

Make any changes to paths contained within the script to suit your system's configuration.

Finally, execute the script.

#+begin_src bash
git_sync.sh
#+end_src
